
import {
    PieChartOutlined,
    UserOutlined,
    HeartFilled,
    ScheduleFilled,
    MailFilled
} from "@ant-design/icons";

export const menus = [
    {
        title:"首页",
        path:"/home/shouye",
        icon:PieChartOutlined
    },
    {
        title:"个人信息",
        path:"/home/user",
        icon:UserOutlined
    },
    {
        title:"体温管理",
        path:"/home/tiwen",
        icon:HeartFilled,
        children:[
            {
                title:"登记体温",
                path:"/home/tiwen/dengji",
                icon:HeartFilled
            },
            {
                title:"体温记录",
                path:"/home/tiwen/jilu",
                icon:HeartFilled
            }
        ]    
    },
    {
        title:"每日签到",
        path:"/home/qiandao",
        icon:ScheduleFilled,
        children:[
            {
                title:"签到",
                path:"/home/qiandao/q",
                icon:ScheduleFilled
            },
            {
                title:"记录",
                path:"/home/qiandao/j",
                icon:ScheduleFilled
            }
        ]
    },
    {
        title:"意见信箱",
        path:"/home/advice",
        icon:MailFilled,
        children:[
            {
                title:"意见反馈",
                path:"/home/advice/fankui",
                icon:MailFilled
            },
            {
                title:"意见记录",
                path:"/home/advice/adjl",
                icon:MailFilled
            }
        ]
    }
]